service: sentenceio

provider:
  name: aws
  runtime: provided
  region: eu-central-1

functions:
  sentenceio:
    handler: ./bootstrap
    events:
      - httpApi:
          path: /
          method: POST
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES