service: sentenceio

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: provided
  region: eu-central-1

functions:
  sentenceio:
    handler: bootstrap
    package:
      artifact: ./dist/bootstrap.zip
      individually: true
      exclude:
        - '**/**'
      include:
        - ./dist/**
    events:
      - httpApi:
          path: /
          method: POST
          request:
            template: application/json