name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  NODE_VERSION: '14.18.2'
  BINARY_NAME: bootstrap


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target $BUILD_TARGET --release
      - uses: actions/upload-artifact@v2
        with:
          path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*
#      - name: Compile
#        run: docker build -o build .
#      - run: |
#          ls -la
#          ls -la build
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          path: build/bootstrap.zip
#          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*

      - uses: papeloto/action-zip@v1
        with:
          files: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*
          dest: artifacts/bootstrap.zip

      - name: Deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}