name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  BUILD_TARGET: x86_64-unknown-linux-musl
  NODE_VERSION: '14.18.2'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: docker build -o . .
      - run: |
          mkdir artifacts
          tar -czf ./artifacts/bootstrap.tar.gz bootstrap
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-sentenceio
          path: ./artifacts/bootstrap.tar
      - name: Deploy
        uses: serverless/github-action@master
        with:
          args: -c "tar -xf ./artifacts/bootstrap.tar.gz ./dist && zip -j ./dist/bootstrap.zip ./dist/bootstrap && sls deploy"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}