name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  BUILD_TARGET: x86_64-unknown-linux-musl
  NODE_VERSION: '14.18.2'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Install Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: Install dependencies
#        run: npm run docker
      - name: Deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}