name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  BUILD_TARGET: x86_64-unknown-linux-musl
  NODE_VERSION: '14.18.2'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - name: Compile
        run: docker build -o ${{ github.workspace }}/build .
      - run: |
          ls -la
          ls -la build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/bootstrap.zip
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/download-artifact@v2
        with:
          path: build
      - run: ls -la
      - name: Deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}