name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  BUILD_TARGET: x86_64-unknown-linux-musl

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build-musl
        uses: gmiam/rust-musl-action@main
        with:
          args: cargo build --target $BUILD_TARGET --release
      - name: Checkout
        uses: actions/checkout@v2
      - name: Builds and deploy
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}