name: Deploy main branch

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Add linux-musl target
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt install musl-tools pkg-config libssl-dev
          cargo clean
          OPENSSL_LIB_DIR="/usr/lib/x86_64-linux-gnu"
          OPENSSL_INCLUDE_DIR="/usr/include/openssl"
      # Build test rust lambda
      - name: Build test rust lambda
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-musl -p sentence_io_service_test
      - run: mv target/x86_64-unknown-linux-musl/release/bootstrap test/bootstrap

      - run: npm install
      - run: npm install -g serverless
      - name: Serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}